apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: conformance-trigger-no-subscriber-ref
  namespace: default
spec:
  broker: comformance-broker
  subscriber:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: my-non-existent-service